In [1]:
# Salvatore D'Acunto | Joe Heesacker | Jenna Swanson | Terrence White - Assignment 10

import pandas as pd

df = pd.read_excel('Medicare_Provider_Charge_Inpatient_DRGALL_FY2016.xlsx', skiprows=5)

df.head()

,DRG Definition,Provider Id,Provider Name,Provider Street Address,Provider City,Provider State,Provider Zip Code,Hospital Referral Region (HRR) Description,Total Discharges,Average Covered Charges,Average Total Payments,Average Medicare Payments
0,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,10033,UNIVERSITY OF ALABAMA HOSPITAL,619 SOUTH 19TH STREET,BIRMINGHAM,AL,35233,AL - Birmingham,13,1.016806e+06,296937.000000,150139.692308
1,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,30103,MAYO CLINIC HOSPITAL,5777 EAST MAYO BOULEVARD,PHOENIX,AZ,85054,AZ - Phoenix,26,4.433875e+05,215059.538462,163889.307692
2,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,40114,BAPTIST HEALTH MEDICAL CENTER-LITTLE ROCK,"9601 INTERSTATE 630, EXIT 7",LITTLE ROCK,AR,72205,AR - Little Rock,33,7.114720e+05,180315.545455,145192.606061
3,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,50025,UC SAN DIEGO HEALTH HILLCREST - HILLCREST MED CTR,200 WEST ARBOR DRIVE,SAN DIEGO,CA,92103,CA - San Diego,17,7.963438e+05,299244.411765,270131.588235
4,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,50100,SHARP MEMORIAL HOSPITAL,7901 FROST ST,SAN DIEGO,CA,92123,CA - San Diego,13,1.434651e+06,239537.461538,215205.000000

In [2]:
# Number of Unique Hospitals

print(len(df['Provider Name'].unique()))

3099

In [3]:
### Number of Unique Hospitals in AR & AK

arak = df[df['Provider State'].isin(['AR', 'AK'])]
print(len(arak['Provider Name'].unique()))

51

In [4]:
# Average cost of DRG 001 in FL at each of the 5 hospitals

fl = df[df['Provider State'].isin(['FL'])]
fl001 = fl[fl['DRG Definition'].isin(['001 - HEART TRANSPLANT OR IMPLANT OF HEART ASSIST SYSTEM W MCC'])]
avg_cost_001 = fl001[['Provider Name', 'Average Total Payments']]
avg_cost_001

                Provider Name  Average Total Payments
14           FLORIDA HOSPITAL           189464.000000
15  JACKSON MEMORIAL HOSPITAL           301640.466667
16  UF HEALTH SHANDS HOSPITAL           211545.133333
17     TAMPA GENERAL HOSPITAL           198471.083333
18                MAYO CLINIC           321528.100000